apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloud-native-demo
  namespace: argocd
spec:
  description: Cloud Native Demo Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: cloud-native-demo
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  orphanedResources:
    warn: false
