#!/bin/bash

echo "=========================================="
echo "Cloud Native Demo - 功能演示"
echo "=========================================="
echo ""

echo "本脚本将演示项目的所有功能："
echo "1. 项目结构"
echo "2. 本地运行"
echo "3. Docker 部署"
echo "4. 版本追溯"
echo "5. 发布策略"
echo "6. 安全扫描"
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "1. 项目结构"
echo "=========================================="
echo ""
echo "查看项目文件结构："
tree -L 3 -I 'node_modules' . 2>/dev/null || find . -type f -not -path '*/node_modules/*' | head -30
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "2. 应用功能"
echo "=========================================="
echo ""
echo "应用提供以下 API 端点："
echo "  - GET /           : 欢迎页面"
echo "  - GET /health     : 健康检查"
echo "  - GET /info       : 版本信息（包含 commit 和 build time）"
echo "  - GET /metrics    : Prometheus 指标"
echo ""

echo "版本信息示例："
cat << 'EOF'
{
  "version": "1.0.0",
  "commit": "abc123def456",
  "buildTime": "2024-01-01T00:00:00Z",
  "environment": "production"
}
EOF
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "3. CI/CD 流水线"
echo "=========================================="
echo ""
echo "GitHub Actions 工作流包含以下阶段："
echo ""
echo "阶段 1: Test & Lint"
echo "  - 运行 ESLint 代码检查"
echo "  - 运行 Jest 单元测试"
echo "  - 上传测试覆盖率"
echo ""
echo "阶段 2: Security Scan"
echo "  - Trivy 漏洞扫描（文件系统和 Docker 镜像）"
echo "  - npm audit 依赖检查"
echo "  - 上传扫描结果到 GitHub Security"
echo ""
echo "阶段 3: Build & Push"
echo "  - 构建 Docker 镜像"
echo "  - 推送到 GitHub Container Registry"
echo "  - 添加版本标签（branch, sha, latest）"
echo ""
echo "阶段 4: Deploy"
echo "  - 更新 Kubernetes Deployment"
echo "  - 等待滚动更新完成"
echo "  - 验证部署状态"
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "4. 版本追溯链路"
echo "=========================================="
echo ""
echo "完整的版本追溯链路："
echo ""
echo "运行实例 (Pod)"
echo "    ↓"
echo "镜像 Tag (cloud-native-demo:v1.0.0)"
echo "    ↓"
echo "Commit SHA (abc123def456)"
echo "    ↓"
echo "代码仓库 (GitHub)"
echo ""
echo "使用 trace.sh 脚本查看完整追溯链路："
echo "  ./scripts/trace.sh"
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "5. 发布策略"
echo "=========================================="
echo ""
echo "项目支持三种发布策略："
echo ""
echo "1. 滚动更新 (Rolling Update)"
echo "   - 逐个替换 Pod"
echo "   - 零停机时间"
echo "   - 命令: ./scripts/strategy.sh rolling <image>"
echo ""
echo "2. 蓝绿部署 (Blue-Green)"
echo "   - 维护两套完整环境"
echo "   - 瞬间切换流量"
echo "   - 快速回滚"
echo "   - 命令: ./scripts/strategy.sh blue-green <image>"
echo ""
echo "3. 金丝雀发布 (Canary)"
echo "   - 小部分流量验证新版本"
echo "   - 逐步扩大流量"
echo "   - 降低风险"
echo "   - 命令: ./scripts/strategy.sh canary <image>"
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "6. 部署管理"
echo "=========================================="
echo ""
echo "使用 deploy.sh 脚本管理部署："
echo ""
echo "部署新版本:"
echo "  ./scripts/deploy.sh deploy cloud-native-demo:v1.0.0"
echo ""
echo "回滚到上一版本:"
echo "  ./scripts/deploy.sh rollback"
echo ""
echo "查看部署状态:"
echo "  ./scripts/deploy.sh status"
echo ""
echo "查看部署历史:"
echo "  ./scripts/deploy.sh history"
echo ""
echo "追踪特定 Pod 的版本:"
echo "  ./scripts/deploy.sh trace <pod-name>"
echo ""
echo "查看应用日志:"
echo "  ./scripts/deploy.sh logs"
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "7. 安全扫描"
echo "=========================================="
echo ""
echo "项目包含多层安全检查："
echo ""
echo "本地安全扫描:"
echo "  ./scripts/security-scan.sh"
echo ""
echo "扫描内容包括："
echo "  - npm audit: 检查 npm 包漏洞"
echo "  - ESLint: 代码质量检查"
echo "  - Trivy: 文件系统漏洞扫描"
echo "  - Trivy: Docker 镜像漏洞扫描"
echo ""
echo "CI/CD 自动扫描:"
echo "  - GitHub Actions 自动执行所有安全检查"
echo "  - 扫描结果上传到 GitHub Security"
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "8. Kubernetes 配置"
echo "=========================================="
echo ""
echo "Kubernetes 资源："
echo ""
echo "命名空间: cloud-native-demo"
echo "部署: 3 个副本"
echo "服务: LoadBalancer (端口 80 -> 3000)"
echo "自动扩缩容: 2-10 个副本"
echo "健康检查: Liveness 和 Readiness 探针"
echo ""
echo "部署命令:"
echo "  kubectl apply -f k8s/"
echo ""
echo "查看状态:"
echo "  kubectl get all -n cloud-native-demo"
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "9. 快捷命令 (Makefile)"
echo "=========================================="
echo ""
echo "make install      - 安装依赖"
echo "make test         - 运行测试"
echo "make lint         - 代码检查"
echo "make build        - 构建 Docker 镜像"
echo "make run          - 本地运行应用"
echo "make docker-up    - 启动 Docker Compose"
echo "make docker-down  - 停止 Docker Compose"
echo "make deploy       - 部署到 Kubernetes"
echo "make rollback     - 回滚部署"
echo "make trace        - 版本追溯"
echo "make security     - 安全扫描"
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "10. 快速开始"
echo "=========================================="
echo ""
echo "方式 1: 使用快速启动脚本（推荐）"
echo "  ./quick-start.sh"
echo ""
echo "方式 2: 手动启动"
echo "  npm install"
echo "  docker-compose up -d"
echo ""
echo "方式 3: 本地运行"
echo "  npm install"
echo "  npm start"
echo ""
echo "访问应用:"
echo "  http://localhost:3000"
echo ""

read -p "按 Enter 键继续..."

echo ""
echo "=========================================="
echo "演示完成！"
echo "=========================================="
echo ""
echo "下一步："
echo "1. 阅读 README.md 了解详细使用方法"
echo "2. 阅读 INSTALL.md 了解环境安装"
echo "3. 阅读 STRUCTURE.md 了解项目结构"
echo "4. 运行 ./quick-start.sh 快速启动项目"
echo ""
