events {
    worker_connections 1024;
}

http {
    upstream stable {
        server stable:3000;
    }

    upstream canary {
        server canary:3000;
    }

    split_clients $remote_addr $backend {
        0% canary;
        * stable;
    }

    server {
        listen 8080;
        
        location / {
            proxy_pass http://$backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
